// Builds two separate RepRapFirmware (Duet) G-code programs from the analyzed
// geometry:
//   1. Hold-down holes program  - bores every small screw hole through the sheet.
//   2. Outlines program         - cuts big feature holes, then each panel's outer
//                                  profile, through the sheet.
// No M3/M5 spindle commands - this machine has a manually-switched router, so
// the files just remind the operator to switch it on.

// Single extension point for tool geometry: right now only a flat end mill is
// supported (constant radius). A ball-nose or V-bit would plug in here later by
// making this depend on cut depth instead of returning a constant.
function getToolRadius(params) {
  return params.toolDiameter / 2;
}

function computePassDepths(totalDepth, stepdown) {
  const passes = [];
  let z = 0;
  while (z < totalDepth - 1e-6) {
    z = Math.min(z + stepdown, totalDepth);
    passes.push(z);
  }
  return passes;
}

function fmt(n) {
  return (Math.round(n * 1000) / 1000).toString();
}

function header(title, params) {
  return [
    `; ${title}`,
    `; Generated by stl2gcode - ${new Date().toISOString()}`,
    `; Tool: ${params.toolDiameter}mm flat end mill (single flute)`,
    `; Material thickness: ${params.materialThickness}mm, cut-through extra: ${params.cutThroughExtra}mm`,
    `; Z=0 is assumed to be the TOP of the material. Re-zero if your setup differs.`,
    `; MANUAL ROUTER - no M3/M5 in this file. Switch the Makita on before running.`,
    `G21 ; mm`,
    `G90 ; absolute positioning`,
    `G17 ; XY plane`,
    `G0 Z${fmt(params.safeZ)}`
  ].join('\n');
}

function transform(pt, params) {
  return [pt[0] - params.originOffset.x, pt[1] - params.originOffset.y];
}

function transformCentroid(loop, params) {
  const [x, y] = transform([loop.centroid.x, loop.centroid.y], params);
  return { x, y };
}

function transformLoopForOffset(loop, params) {
  if (loop.isCircle) {
    const [cx, cy] = transform([loop.centroid.x, loop.centroid.y], params);
    return { isCircle: true, centroid: { x: cx, y: cy }, circleRadius: loop.circleRadius, area: loop.area };
  }
  return { isCircle: false, centroid: transformCentroid(loop, params), points: loop.points.map(p => transform(p, params)), area: loop.area };
}

// ---- Hold-down holes program (true helical entry - one continuous turn per pass) ----

function buildHolesProgram(smallHoles, params) {
  const toolRadius = getToolRadius(params);
  const totalDepth = params.materialThickness + params.cutThroughExtra;
  const passDepths = computePassDepths(totalDepth, params.stepdown);

  const holesSorted = smallHoles.slice().sort((a, b) => {
    const [, ay] = transform([a.centroid.x, a.centroid.y], params);
    const [, by] = transform([b.centroid.x, b.centroid.y], params);
    return ay - by;
  });

  const lines = [header('Swift box - hold-down holes', params)];
  lines.push(`; ${holesSorted.length} hold-down hole(s), tool radius ${fmt(toolRadius)}mm`);

  for (const hole of holesSorted) {
    const [cx, cy] = transform([hole.centroid.x, hole.centroid.y], params);
    const pathRadius = hole.circleRadius - toolRadius;

    lines.push(`; hole at (${fmt(cx)}, ${fmt(cy)}) dia=${fmt(hole.circleRadius * 2)}mm`);
    lines.push(`G0 Z${fmt(params.safeZ)}`);

    if (pathRadius > 0.05) {
      const startX = cx + pathRadius, startY = cy;
      lines.push(`G0 X${fmt(startX)} Y${fmt(startY)}`);
      lines.push(`G1 Z0 F${params.plungeRate}`);
      for (const z of passDepths) {
        // Helical: one full turn descending from the previous depth to this one,
        // in a single arc move (Z differs between the arc's start and end).
        lines.push(`G2 X${fmt(startX)} Y${fmt(startY)} Z${fmt(-z)} I${fmt(-pathRadius)} J0 F${params.plungeRate}`);
      }
    } else {
      // Hole is ~tool size: no room to circle-mill, just peck-drill at center.
      lines.push(`G0 X${fmt(cx)} Y${fmt(cy)}`);
      for (const z of passDepths) {
        lines.push(`G1 Z${fmt(-z)} F${params.plungeRate}`);
      }
    }
    lines.push(`G0 Z${fmt(params.safeZ)}`);
  }

  lines.push(`; end of file`);
  return lines.join('\n') + '\n';
}

// ---- Path walking / ramped entry ----
//
// A path is { start:[x,y], segments:[{type:'line',to} | {type:'arc',to,center,radius,ccw}] }
// (this is exactly what offsetLoop()/offsetPolygon() produce, in machine coordinates).
//
// Ramping means: descend gradually over the first `rampLength` of the path
// instead of plunging straight down, then cut the rest of the loop flat at
// depth, then - since that initial stretch only got cut at an angle, not full
// depth - retrace just that same initial stretch once more, flat, to clean it
// up. G-code does the interpolation for us: a line or arc move that specifies
// a different Z at its end than its start is already a ramp/helix, no need to
// chop it into many small steps.

function segmentLength(from, seg) {
  if (seg.type === 'line') return Math.hypot(seg.to[0] - from[0], seg.to[1] - from[1]);
  const a1 = Math.atan2(from[1] - seg.center[1], from[0] - seg.center[0]);
  let a2 = Math.atan2(seg.to[1] - seg.center[1], seg.to[0] - seg.center[0]);
  let sweep = a2 - a1;
  if (seg.ccw && sweep < 0) sweep += 2 * Math.PI;
  if (!seg.ccw && sweep > 0) sweep -= 2 * Math.PI;
  return Math.abs(sweep) * seg.radius;
}

// Splits a segment at fraction `t` (0..1) along its length, returning
// [beforePart, afterPart] as two segments of the same type covering the same
// ground as the original.
function splitSegment(from, seg, t) {
  if (seg.type === 'line') {
    const mid = [from[0] + (seg.to[0] - from[0]) * t, from[1] + (seg.to[1] - from[1]) * t];
    return [{ type: 'line', to: mid }, { type: 'line', to: seg.to }];
  }
  const a1 = Math.atan2(from[1] - seg.center[1], from[0] - seg.center[0]);
  let a2 = Math.atan2(seg.to[1] - seg.center[1], seg.to[0] - seg.center[0]);
  let sweep = a2 - a1;
  if (seg.ccw && sweep < 0) sweep += 2 * Math.PI;
  if (!seg.ccw && sweep > 0) sweep -= 2 * Math.PI;
  const aMid = a1 + sweep * t;
  const mid = [seg.center[0] + seg.radius * Math.cos(aMid), seg.center[1] + seg.radius * Math.sin(aMid)];
  return [
    { type: 'arc', to: mid, center: seg.center, radius: seg.radius, ccw: seg.ccw },
    { type: 'arc', to: seg.to, center: seg.center, radius: seg.radius, ccw: seg.ccw }
  ];
}

function emitMove(seg, z, feed, lines) {
  const zPart = (z === null) ? '' : ` Z${fmt(z)}`;
  if (seg.type === 'line') {
    lines.push(`G1 X${fmt(seg.to[0])} Y${fmt(seg.to[1])}${zPart} F${feed}`);
  } else {
    const gcode = seg.ccw ? 'G3' : 'G2';
    const from = seg._from;
    lines.push(`${gcode} X${fmt(seg.to[0])} Y${fmt(seg.to[1])}${zPart} I${fmt(seg.center[0] - from[0])} J${fmt(seg.center[1] - from[1])} F${feed}`);
  }
}

// Cuts one full pass of `path` at depth `targetZ`, ramping down from
// `startZ` over `rampLength` of path travel if rampLength > 0 (0 = the old
// straight-plunge behaviour).
function emitPass(path, startZ, targetZ, rampLength, feed, lines) {
  let pos = path.start;
  let traveled = 0;
  let rampDone = rampLength <= 1e-6;
  const rampMoves = []; // the initial stretch, recorded so it can be re-cut flat afterwards

  // Caller is responsible for already being at path.start, at startZ, before
  // calling this - see emitPathAllPasses. (Cutting a direct line to get here
  // instead would shortcut across whatever the path's actual shape is - fine
  // if it's convex, wrong wherever it isn't, e.g. across a tab or notch.)
  if (!rampDone) lines.push(`; ramped entry over ${fmt(rampLength)}mm`);

  for (const rawSeg of path.segments) {
    let seg = Object.assign({ _from: pos }, rawSeg);
    if (!rampDone) {
      const len = segmentLength(pos, seg);
      if (traveled + len < rampLength) {
        const z = startZ + (targetZ - startZ) * ((traveled + len) / rampLength);
        emitMove(seg, z, feed, lines);
        rampMoves.push(Object.assign({ from: pos }, rawSeg));
        traveled += len;
        pos = seg.to;
        continue;
      } else {
        const t = (rampLength - traveled) / len;
        const [beforePart, afterPart] = splitSegment(pos, seg, t);
        emitMove(Object.assign({ _from: pos }, beforePart), targetZ, feed, lines);
        rampMoves.push({ from: pos, type: beforePart.type, to: beforePart.to, center: beforePart.center, radius: beforePart.radius, ccw: beforePart.ccw });
        const afterFrom = beforePart.to;
        emitMove(Object.assign({ _from: afterFrom }, afterPart), null, feed, lines);
        pos = afterPart.to;
        rampDone = true;
        continue;
      }
    }
    emitMove(seg, null, feed, lines);
    pos = seg.to;
  }

  // The loop is closed now (pos === path.start). Re-cut the ramped stretch
  // once more, flat this time, since it was only cut at an angle above.
  for (const m of rampMoves) {
    emitMove(Object.assign({ _from: m.from }, m), null, feed, lines);
  }
}

// Cuts `path` through every depth in passDepths, ramping into each new depth
// from the previous one (the very first pass ramps down from Z0).
function emitPathAllPasses(path, passDepths, params, lines, rampLengthOverride) {
  const rampLength = rampLengthOverride !== undefined ? rampLengthOverride : rampRunLength(params);
  let prevZ = 0;
  for (const z of passDepths) {
    // Retract and reposition above the material before every pass, not just
    // the first - going straight from wherever the last pass ended to
    // path.start along a lateral in-material line isn't guaranteed to follow
    // the path's own shape (see the bug this fixed).
    lines.push(`G0 Z${fmt(params.safeZ)}`);
    lines.push(`G0 X${fmt(path.start[0])} Y${fmt(path.start[1])}`);
    lines.push(`G1 Z${fmt(prevZ)} F${params.plungeRate}`);
    emitPass(path, prevZ, -z, rampLength, params.feedRate, lines);
    prevZ = -z;
  }
  lines.push(`G0 Z${fmt(params.safeZ)}`);
}

function rampRunLength(params) {
  const angle = (params.rampAngleDeg || 10) * Math.PI / 180;
  return params.stepdown / Math.tan(angle);
}

function emitCircleAllPasses(circlePath, passDepths, params, lines) {
  const { center, radius } = circlePath;
  const startX = center.x + radius, startY = center.y;
  lines.push(`G0 Z${fmt(params.safeZ)}`);
  lines.push(`G0 X${fmt(startX)} Y${fmt(startY)}`);
  lines.push(`G1 Z0 F${params.plungeRate}`);
  let prevZ = 0;
  for (const z of passDepths) {
    lines.push(`G2 X${fmt(startX)} Y${fmt(startY)} Z${fmt(-z)} I${fmt(-radius)} J0 F${params.plungeRate}`);
    prevZ = z;
  }
  lines.push(`G0 Z${fmt(params.safeZ)}`);
}

function emitClosedPath(offsetPath, passDepths, params, lines) {
  if (offsetPath.isCircle) {
    emitCircleAllPasses(offsetPath, passDepths, params, lines);
  } else {
    emitPathAllPasses(offsetPath.path, passDepths, params, lines);
  }
}

// ---- Rough + finish (skips roughing when there's not enough clearance to matter) ----

function roughOffsetIsViable(loop, roughDistance) {
  if (loop.isCircle) {
    const roughRadius = loop.circleRadius + roughDistance;
    return roughRadius > 0.1; // a real, cuttable circle remains
  }
  // For a polygon, a collapsed/inverted rough offset shows up as area that's
  // vanished or gone negative relative to the finish offset - cheap and
  // direction-agnostic, so it works the same for growing or shrinking.
  const roughPath = offsetPolygon(loop.points, roughDistance);
  const roughPts = flattenPathToPoints(roughPath);
  const roughArea = Math.abs(shoelaceArea(roughPts));
  return roughArea > loop.area * 0.05;
}

function shoelaceArea(points) {
  let a = 0;
  for (let i = 0; i < points.length; i++) {
    const p1 = points[i], p2 = points[(i + 1) % points.length];
    a += p1[0] * p2[1] - p2[0] * p1[1];
  }
  return a / 2;
}

// Cuts `loop` (already in machine coordinates) as a rough pass (extra offset
// left as a margin) followed by a finish pass at the true tool-radius offset -
// or just the finish pass alone, if there isn't enough room for roughing to
// make sense (e.g. a hole barely bigger than the tool).
function cutFeatureRoughFinish(loop, isHole, passDepths, params, lines) {
  const toolRadius = getToolRadius(params);
  const sign = isHole ? -1 : 1;
  const finishDistance = sign * toolRadius;
  const roughExtra = params.roughingExtra || 0;

  if (roughExtra > 0) {
    const roughDistance = finishDistance + sign * roughExtra;
    if (roughOffsetIsViable(loop, roughDistance)) {
      lines.push(`; rough pass (+${fmt(roughExtra)}mm)`);
      emitClosedPath(offsetLoop(loop, roughDistance), passDepths, params, lines);
    } else {
      lines.push(`; rough pass skipped - not enough clearance for a ${fmt(roughExtra)}mm rough offset here`);
    }
  }
  lines.push(`; finish pass`);
  emitClosedPath(offsetLoop(loop, finishDistance), passDepths, params, lines);
}

// ---- Pockets: raster-clear the interior, then rough+finish the wall ----

function emitPocketClear(pocket, params, lines) {
  const toolRadius = getToolRadius(params);
  const finishAllowance = 0.1; // mm of wall left for the finishing pass to clean up
  const stepoverPct = (params.pocketStepoverPct || 70) / 100;
  const stepover = params.toolDiameter * stepoverPct;

  const machineLoop = {
    isCircle: false,
    centroid: transformCentroid(pocket.loop, params),
    points: pocket.loop.points.map(p => transform(p, params)),
    area: pocket.loop.area
  };

  const passDepths = computePassDepths(pocket.depth, params.stepdown);

  lines.push(`; pocket clear, depth ${fmt(pocket.depth)}mm`);
  const roughPath = offsetPolygon(machineLoop.points, -(toolRadius + finishAllowance));
  const roughPts = flattenPathToPoints(roughPath);
  for (const z of passDepths) {
    const segments = rasterFillPolygon(roughPts, stepover);
    if (segments.length === 0) continue;
    lines.push(`G0 Z${fmt(params.safeZ)}`);
    lines.push(`G0 X${fmt(segments[0].x1)} Y${fmt(segments[0].y1)}`);
    lines.push(`G1 Z${fmt(-z)} F${params.plungeRate}`);
    for (const seg of segments) {
      lines.push(`G1 X${fmt(seg.x1)} Y${fmt(seg.y1)} F${params.feedRate}`);
      lines.push(`G1 X${fmt(seg.x2)} Y${fmt(seg.y2)} F${params.feedRate}`);
    }
    lines.push(`G0 Z${fmt(params.safeZ)}`);
  }

  lines.push(`; pocket wall`);
  cutFeatureRoughFinish(machineLoop, true, passDepths, params, lines);
}

// ---- Outlines program ----

function buildOutlinesProgram(parts, params, smallHoleAreaThreshold) {
  const toolRadius = getToolRadius(params);
  const totalDepth = params.materialThickness + params.cutThroughExtra;
  const passDepths = computePassDepths(totalDepth, params.stepdown);

  const partsSorted = parts.slice().sort((a, b) => (a.bbox.minY - b.bbox.minY) || (a.bbox.minX - b.bbox.minX));

  const lines = [header('Swift box - outlines', params)];
  lines.push(`; ${partsSorted.length} part(s), tool radius ${fmt(toolRadius)}mm`);

  for (const part of partsSorted) {
    lines.push(`; --- part bbox (${fmt(part.bbox.minX)},${fmt(part.bbox.minY)}) size ${fmt(part.bbox.maxX - part.bbox.minX)}x${fmt(part.bbox.maxY - part.bbox.minY)} ---`);

    // Complement of the holes program's selection (area < threshold AND circular) -
    // anything that isn't going to the hold-down program must land here, including
    // the rare small-but-not-quite-circular edge case, so nothing gets silently dropped.
    const featureHoles = part.holes.filter(h => !(h.area < smallHoleAreaThreshold && h.isCircle));
    for (const hole of featureHoles) {
      lines.push(`; feature hole, dia~${fmt((hole.circleRadius || Math.sqrt(hole.area / Math.PI)) * 2)}mm`);
      const machineHole = transformLoopForOffset(hole, params);
      cutFeatureRoughFinish(machineHole, true, passDepths, params, lines);
    }

    for (const pocket of part.pockets) {
      emitPocketClear(pocket, params, lines);
    }

    lines.push(`; outer profile`);
    const machineOuter = transformLoopForOffset(part.outer, params);
    cutFeatureRoughFinish(machineOuter, false, passDepths, params, lines);
  }

  lines.push(`; end of file`);
  return lines.join('\n') + '\n';
}
